import type { Metadata } from 'next';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { AppStoreProvider } from './providers';

export const metadata: Metadata = {
  title: 'Cornbun',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head>
        <title>Cornbun</title>
      </head>
      <body>
        <AppStoreProvider>
          <AntdRegistry>{children}</AntdRegistry>
        </AppStoreProvider>
      </body>
    </html>
  );
}
